### ISSUE TITLE
Can't seem to find tabnine for jupyterlab

### ISSUE THREAD

**Issue by Logan1x** [codota/jupyter-tabnine#55]
Do we have tabnine for jupyterlab? Its awesome extension, but looks like still available for jupyterlab.

**Comment by pacospace** [comment]
https://github.com/codota/jupyter-tabnine/issues/7

**Comment by hyspacex** [comment]
any updates on this?

**Comment by maya-tabnine** [comment]
There is no Tabnine extension for JupyterLab yet, but it is definitely on our roadmap!

**Comment by xinwei-sher** [comment]
It 's a great extension. Works only on Jupyter Notebook, though.  Please make it also available on Jupyterlab! Thank you!

**Comment by xinwei-sher** [comment]
You could be a real competitor with Kite!

**Comment by FrannieK** [comment]
very looking forward to seeing the extension for lab!!

**Comment by drandran12** [comment]
Yes, that would be awesome!

**Comment by dimacodota** [comment]
Hi All, we just released a jupyterlab extension https://github.com/codota/tabnine-jupyterlab 🎉
