### ISSUE TITLE
Feature request: option to change text color

### ISSUE THREAD

**Issue by FelixAbrahamsson** [codota/jupyter-tabnine#63]
I use a dark theme from jupyterthemes and it's very difficult to see the text suggestions from TabNine. Would be great to be able to change the text color!

**Comment by boaz-codota** [comment]
That is an awesome idea!

We will prioritize on that, for future releases.

**Comment by 7benson** [comment]
> I use a dark theme from jupyterthemes and it's very difficult to see the text suggestions from TabNine. Would be great to be able to change the text color!

**We can just change the color of the suggestions in custom.css file** 

- In Windows, find config directory by running a command: jupyter --config-dir
- 
- In Linux it is ~/.jupyter
- 
- If there no " custom " folder, create a folder with name custom and in that folder, create a custom.css file, If you already have the custom.css file, no need to do this
- 
- Add these css lines at the beginning of the custom.css file and refresh the jupyter-notebook

```
.completions ,.complete-dropdown-content{
    color:black !important;
}
```
