### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by YIMINGMA** [codota/jupyter-tabnine#70]
Hi, developers. 

I have tried everything in your documentation, but when I typed `jupyter-notebook` in my terminal, I got messages below: 
```
[INFO 2021-06-14 22:03:29.633 TabNineDownloader]: Begin to download TabNine Binary from https://update.tabnine.com/3.2.28/arm64-apple-darwin/TabNine

[ERROR 2021-06-14 21:59:40.915 TabNineDownloader]: Download failed, error: HTTP Error 403: Forbidden
```

So, I guess this might be a problem with the server?

gz#1756

**Comment by maya-tabnine** [comment]
Did you try to install it using the instructions at https://github.com/codota/jupyter-tabnine#installation ?
At what command did you receive the error reported?

**Comment by chirag-mehta** [comment]
<img width="1260" alt="Screenshot 2021-06-24 at 7 53 04 AM" src="https://user-images.githubusercontent.com/29609746/123192810-40733200-d4c1-11eb-8d29-f9a1b9200a87.png">

Getting this when starting the jupyter server. I don't get any suggestions when I use it in a notebook even though the extension is enabled. I used the install instructions in the link you posted here.

**Comment by maya-tabnine** [comment]
Please follow the instruction at https://github.com/codota/jupyter-tabnine/blob/master/DEBUG.md and send us the output.

**Comment by bilucodota** [comment]
Hi @YIMINGMA sorry for the late response. PR #66 should solve this issue. Can you replace `tabnine.py` (under `/Users/chiragmehta/.../jupyter-tavbube/` with `tabnine.py` from the PR? Let us know if it works for you
